#!/usr/bin/env bash
# SessionStart hook: prints live, volatile project state so a fresh context window is
# oriented without manual prompting. Static facts live in CLAUDE.md (auto-loaded).
# Output goes to stdout, which Claude Code injects into the session context.

set -euo pipefail
Root="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$Root" || exit 0

echo "=== Hex live state (generated by .claude/Context.sh) ==="
echo

echo "Root branch: $(git branch --show-current 2>/dev/null || echo '?')"
Dirty="$(git status --porcelain 2>/dev/null)"
if [ -n "$Dirty" ]; then
  echo "Uncommitted changes in root:"
  echo "$Dirty" | sed 's/^/  /'
else
  echo "Root working tree clean."
fi
echo

echo "Submodule pins:"
git submodule status 2>/dev/null | sed 's/^/  /' || echo "  (none)"
for Sub in Backend Frontend; do
  if [ -d "$Sub/.git" ] || [ -f "$Sub/.git" ]; then
    SubDirty="$(git -C "$Sub" status --porcelain 2>/dev/null)"
    [ -n "$SubDirty" ] && echo "  $Sub has uncommitted changes ($(echo "$SubDirty" | wc -l | tr -d ' ') files)"
  fi
done
echo

# The newest planning doc is the active spec; surface it explicitly.
Latest="$(ls -t additions.md todos*.md prompt.md questions.md 2>/dev/null | head -n1 || true)"
[ -n "$Latest" ] && echo "Active planning doc (newest): $Latest"
echo "Iteration history: summary.txt   |   Conventions: coding-conventions.md   |   Orientation: CLAUDE.md"
